### ISSUE TITLE
Aggregate dataframes from multiple tables 

### ISSUE THREAD

**Issue by alxcost** [datashield/DSOpal#1]
Hello,

I'm trying to run a method through DataSHIELD that requires data from multiple tables defined in Opal. I was wondering if it was possible to aggregate dataframes from multiple tables on the server's side?

In my case the server-side code runs a function from a library that requires a list of multiple tables. The library and function in question is the following: https://immunarch.com/reference/repOverlap.html, where '.data' is the relevant argument.

I've tried passing multiple tables on Opal's login's object (code below) but this seems to load 2 connections, so this ends up splitting the data and calling my function twice.

```
server <- c("server1")
url <- c("https://localhost/opal/repo") 
user <- "superego7"
password <- ""
name <- "name"
table <- c("SRP072206.Patient1-B0", "SRP072206.Patient1-N1") 
my_logindata <- data.frame(server,name,url,user,password,table)
                           
opals <- opal::datashield.login(logins=my_logindata, assign=TRUE)
```

The function on the server's side does the following:
```
repClonalityDS <- function (dataframe) {
  library(dsBase)
  check <- isValidDS(dataframe)

  if (!check) {
    return (NA)
  }
  
  library(immunarch)
  ret <- parse_mixcr(dataframe)
  clonality <- repClonality(ret, .method = "clonal.prop")
  
  return (clonality)
}
```

Would it be possible for that 'dataframe' parameter to contain data from multiple tables?

Thanks

**Comment by ymarcon** [comment]
See the merge function that is being developed by the Datashield team at Newcastle U.: [dsBetaTestClient::ds.merge.o](https://github.com/datashield/dsBetaTestClient/blob/master/R/ds.merge.o.R) (client side) and [dsBetaTest::mergeDS.o](https://github.com/datashield/dsBetaTest/blob/master/R/mergeDS.o.R) (server side). These are in the process of being integrated to the next version of dsBase.
